# Numpy homework

In [3]:
# data generation
import numpy as np
np.random.seed(201)
data = np.random.uniform(-1.9, 2.5, (1000, 2000))
np.savetxt("npdata.txt", data)

In [26]:
data = np.loadtxt("npdata.txt")
print(data.shape)

(1000, 2000)


In [5]:
# print the sum of the 500th column
print(data[:, 499].sum())

305.89188995198646


In [6]:
# print the sum of the 500th row
print(data[499, :].sum())

591.2346963135233


In [7]:
# print the sum of the 500th row, including only columns with indexes 1, 3, 5, ... and exluding the last one
print(data[499, 1:-1:2].sum())

360.7320183140055


In [22]:
# count all elements in the range -0.1 <= x <= 2.1
mask = (data >= -0.1) & (data <= 2.1)
print(np.count_nonzero(data[mask]))

999506


In [23]:
# Crear un arreglo de 10x10 llenos de 1 en el borde y 0 internamente 
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
